services:
  equity-screener:
    build:
      context: .
      dockerfile: Dockerfile
    image: equity-screener:latest
    container_name: equity_screener
    volumes:
      - ./data/outputs:/app/data/outputs
    environment:
      - REGION=Argentina
    command: [ "Argentina" ]
