services:
  yahoo-crawler:
    build:
      context: .
      dockerfile: Dockerfile
    image: yahoo-crawler:latest
    container_name: yahoo_finance_crawler
    volumes:
      - ./data/outputs:/app/data/outputs
    environment:
      - REGION=Argentina
    command: [ "Argentina" ]
